name: Envoi factures du jour

on:
  schedule:
    # GitHub utilise l'heure UTC.
    # 21h Paris en été -> 19h UTC
    - cron: '0 19 * * *'

    # 21h Paris en hiver -> 20h UTC
    - cron: '0 20 * * *'

  workflow_dispatch:
    inputs:
      start_date:
        description: "Date de début (YYYY-MM-DD)"
        required: false
        default: ""

      end_date:
        description: "Date de fin (YYYY-MM-DD)"
        required: false
        default: ""

      dry_run:
        description: "Test à blanc (aucun email envoyé)"
        type: boolean
        default: true

      test_redirect_email:
        description: "Rediriger les emails vers cette adresse"
        type: string
        default: ""

jobs:
  envoi:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node envoi-factures.js
        env:
          SHOP: ${{ secrets.SHOP }}
          SHOPIFY_CLIENT_ID: ${{ secrets.SHOPIFY_CLIENT_ID }}
          SHOPIFY_CLIENT_SECRET: ${{ secrets.SHOPIFY_CLIENT_SECRET }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_NAME: ${{ secrets.SENDER_NAME }}

          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}

          DRY_RUN: ${{ (github.event_name == 'workflow_dispatch' && inputs.dry_run) && '1' || '' }}
          TEST_REDIRECT_EMAIL: ${{ github.event_name == 'workflow_dispatch' && inputs.test_redirect_email || '' }}
